apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: {{ .Vales.pod-label }}
  template:
    metadata:
      labels:
        pod-label: {{ .Vales.pod-label }}
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_DATABASE
          value: nextcloud
        envFrom:
        - secretRef:
            name: nextcloud-db-secret
        volumeMounts:
        -name: db-storage
        mountPath: /var/lib/mysql
        subPath: mysql-data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: podpvc