apiVersion: v1
kind: Service
metadata:
  name: {{ Values.name }}
  labels:
    app: {{ Values.label }}
spec:
  selector:
    pod-label: {{ Values.pod-label }}
  ports:
  - protocol: TCP
    port: 3306