apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        command: ["printenv"]
        args: ["HOSTNAME", "KUBERNETES_PORT"]
        volumeMounts:
        - name: output
          mountPath: /opt
      volumes:
      - hostPath:
          path: {{ .Values.output_path }}
        name: output
