apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: control
      protocol: TCP
      port: {{ .Values.service.controlPort }}
      targetPort: control
    - name: discovery
      protocol: UDP
      port: {{ .Values.service.controlPort }}
      targetPort: discovery