apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ExternalName
  externalName: {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432