apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      protocol: TCP
      port: 8008
      targetPort: 8008