apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery-nodeport
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: app.kubernetes.io/component=jenkins-controller,app.kubernetes.io/instance={{ template "jenkins.fullname" . }}