apiVersion: v1
kind: PersistentVolume
metadata:
  name: am-pv
  namespace: monitor
spec:
  capacity: 
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/am