apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prom
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - prom.uk.to
    secretName: prom-tls
  rules:
  - host: prom.uk.to
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
         service:
          name: prom-prometheus-server
          port:
           number: 80
