apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        securityContext:
              privileged: true
              capabilities:
                add:
                  - SYS_ADMIN
        env:
        - name: KEYBASE_PAPERKEY
          valueFrom:
           secretKeyRef:
            name: arnie-key
            key: KEYBASE_PAPERKEY
        - name: KEYBASE_USERNAME
          value: arnie
        lifecycle:
              postStart:
                exec:
                  command: ["gcsfuse", "-o", "nonempty", "erazum-agurne", "/home/keybase/.config/arnie"]
              preStop:
                exec:
                  command: ["fusermount", "-u", "/home/keybase/.config/arnie"]
