kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-0
  namespace: vault
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi