jenkins:
  systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${chart-admin-username}"
        name: "Jenkins Admin"
        password: "${chart-admin-password}"
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  labelString: ""
  projectNamingStrategy: "standard"
  markupFormatter:
    plainText
  clouds:
  - kubernetes:
      containerCapStr: "10"
      defaultsProviderTemplate: ""
      connectTimeout: "5"
      readTimeout: "15"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      namespace: "jenkins"
      serverUrl: "https://kubernetes.default"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      templates:
        - containers:
          - args: "^${computer.jnlpmac} ^${computer.name}"
            command: "sleep"
            envVars:
            - envVar:
                key: "JENKINS_URL"
                value: "http://jenkins.jenkins.svc.cluster.local:8080/"
            image: "jenkins/inbound-agent:4.6-1"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "jnlp"
            resourceLimitCpu: "512m"
            resourceLimitMemory: "512Mi"
            resourceRequestCpu: "512m"
            resourceRequestMemory: "512Mi"
            workingDir: "/home/jenkins"
          id: "804744a9a9fee3f02a5f7ed39fea229ddb0f98cc22e9ccdd10679f2d441b0813"
          label: "jenkins-jenkins-agent"
          name: "default"
          namespace: "jenkins"
          nodeUsageMode: NORMAL
          podRetention: "never"
          serviceAccount: "default"
          slaveConnectTimeout: 100
          slaveConnectTimeoutStr: "100"
          yamlMergeStrategy: "override"
        - containers:
          - args: "9999999"
            command: "sleep"
            image: "alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "worker"
            workingDir: "/home/jenkins/agent"
          id: "6089ef50-a74b-441f-88dc-92b10c1c7be1"
          label: "k8s-worker"
          name: "worker"
          namespace: "jenkins"
          yamlMergeStrategy: "override"
  - hetzner:
      credentialsId: "hetzner-api-token"
      instanceCapStr: "10"
      name: "hetzner"
      serverTemplates:
      - bootDeadline: 15
        connector:
          root:
            connectionMethod: "public"
            sshCredentialsId: "hetzner-key"
        image: "81302760"
        labelStr: "hetzner-cx11"
        location: "fsn1"
        name: "cx11"
        network: "823122"
        primaryIp: "default"
        serverType: "cx11"
        shutdownPolicy:
          idle:
            idleMinutes: 5
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
unclassified:
  location:
    adminAddress: 
    url: https://blane.uk.to
  globalLibraries:
    libraries:
    - name: "jenkins-dsl"
      retriever:
        modernSCM:
          scm:
            git:
              credentialsId: "github"
              id: "d32a0534-b0ce-497c-8c69-d4e40affdbd9"
              remote: "git@github.com:andycockers/jenkins-dsl.git"
              traits:
              - "gitBranchDiscovery"
jobs:
  - script: >
      job("dsl-create-jobs") {
        label('hetzner-cx11')
        description()
        keepDependencies(false)
        scm {
          git {
            remote {
              github("andycockers/jenkins-dsl", "ssh")
              credentials("github")
              }
              branch("*/main")
              }
              }
        disabled(false)
        concurrentBuild(false)
        steps {
          jobDsl {
            targets 'jobs_lib/*.groovy'
            ignoreExisting(false)
            removeAction("IGNORE")
            removeViewAction("IGNORE")
            lookupStrategy("JENKINS_ROOT")
            }
            }
            }
  - script: >
      job("dsl-create-folders") {
        label('hetzner-cx11')
        description()
        keepDependencies(false)
        scm {
          git {
            remote {
              github("andycockers/jenkins-dsl", "ssh")
              credentials("github")
              }
              branch("*/main")
              }
              }
        disabled(false)
        concurrentBuild(false)
        steps {
          jobDsl {
            targets 'jenkins_folder_structure/jenkins_organisation.groovy'
            }
            }
            }