jenkins:
  systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${chart-admin-username}"
        name: "Jenkins Admin"
        password: "${chart-admin-password}"
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  labelString: ""
  projectNamingStrategy: "standard"
  markupFormatter:
    plainText
  clouds:
  - kubernetes:
      containerCapStr: "10"
      defaultsProviderTemplate: ""
      connectTimeout: "5"
      readTimeout: "15"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      namespace: "jenkins"
      serverUrl: "https://kubernetes.default"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      templates:
        - name: "default"
          namespace: "jenkins"
          id: 804744a9a9fee3f02a5f7ed39fea229ddb0f98cc22e9ccdd10679f2d441b0813
          containers:
          - name: "jnlp"
            alwaysPullImage: false
            args: "^${computer.jnlpmac} ^${computer.name}"
            command: 
            envVars:
              - envVar:
                  key: "JENKINS_URL"
                  value: "http://jenkins.jenkins.svc.cluster.local:8080/"
            image: "jenkins/inbound-agent:4.6-1"
            privileged: "false"
            resourceLimitCpu: 512m
            resourceLimitMemory: 512Mi
            resourceRequestCpu: 512m
            resourceRequestMemory: 512Mi
            runAsUser: 
            runAsGroup: 
            ttyEnabled: false
            workingDir: /home/jenkins
          idleMinutes: 0
          instanceCap: 2147483647
          label: "jenkins-jenkins-agent "
          nodeUsageMode: "NORMAL"
          podRetention: Never
          showRawYaml: true
          serviceAccount: "default"
          slaveConnectTimeoutStr: "100"
          yamlMergeStrategy: override
  - hetzner:
      credentialsId: "hetzner-api-token"
      instanceCapStr: "10"
      name: "hetzner"
      serverTemplates:
      - bootDeadline: 15
        connector:
          root:
            connectionMethod: "public"
            sshCredentialsId: "hetzner-key"
        image: "81302760"
        labelStr: "hetzner-cx11"
        location: "fsn1"
        name: "cx11"
        network: "823122"
        primaryIp: "default"
        serverType: "cx11"
        shutdownPolicy:
          idle:
            idleMinutes: 5
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
unclassified:
  location:
    adminAddress: 
    url: https://blane.uk.to
  globalLibraries:
    libraries:
    - name: "jenkins-dsl"
      retriever:
        modernSCM:
          scm:
            git:
              credentialsId: "github"
              id: "d32a0534-b0ce-497c-8c69-d4e40affdbd9"
              remote: "git@github.com:andycockers/jenkins-dsl.git"
              traits:
              - "gitBranchDiscovery"
jobs:
  - script: >
      job("dsl-create-jobs") {
        label('hetzner-cx11')
        description()
        keepDependencies(false)
        scm {
          git {
            remote {
              github("andycockers/jenkins-dsl", "ssh")
              credentials("github")
              }
              branch("*/main")
              }
              }
        disabled(false)
        concurrentBuild(false)
        steps {
          dsl {
            ignoreExisting(false)
            removeAction("IGNORE")
            removeViewAction("IGNORE")
            lookupStrategy("JENKINS_ROOT")
               }
          jobDsl {
            targets 'jobs_lib/*.groovy'
            }
            }
            }
  - script: >
      job("dsl-create-folders") {
        label('hetzner-cx11')
        description()
        keepDependencies(false)
        scm {
          git {
            remote {
              github("andycockers/jenkins-dsl", "ssh")
              credentials("github")
              }
              branch("*/main")
              }
              }
        disabled(false)
        concurrentBuild(false)
        steps {
          jobDsl {
            targets 'jenkins_folder_structure/jenkins_organisation.groovy'
            }
            }
            }