apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      pod_label: {{ .Values.pod_label}}
  template:
    metadata:
      labels:
        pod_label: {{ .Values.pod_label}}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        volumeMounts:
        - name: server-storage
          mountPath: /var/www/html
          subPath: server-data
      volumes:
      - name: server-storage
        hostPath:
          path: {{ .Values.storage_path }}